### ISSUE TITLE
[noetic] ModuleNotFoundError: No module named 'xmlrpclib'

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros-visualization/rqt_moveit#8]
When trying to open the plugin in rqt, I get the following error:
```
RosPluginProvider.load(rqt_moveit/Moveit) exception raised in __builtin__.__import__(rqt_moveit.moveit_plugin, [MoveitPlugin]):
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 79, in load
    module = __builtin__.__import__(
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_moveit/moveit_plugin.py", line 38, in <module>
    from rqt_moveit.moveit_widget import MoveitWidget
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_moveit/moveit_widget.py", line 38, in <module>
    import xmlrpclib
ModuleNotFoundError: No module named 'xmlrpclib'

PluginManager._load_plugin() could not load plugin "rqt_moveit/Moveit":
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 61, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 90, in load
    raise e
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 79, in load
    module = __builtin__.__import__(
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_moveit/moveit_plugin.py", line 38, in <module>
    from rqt_moveit.moveit_widget import MoveitWidget
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_moveit/moveit_widget.py", line 38, in <module>
    import xmlrpclib
ModuleNotFoundError: No module named 'xmlrpclib'
```
Running rqt_moveit 0.5.9

**Comment by arne48** [comment]
Thank you for reporting this issue and directly providing a fix for it.
I don't see any issues with the fix, so after a quick test I will merge it and publish an update for the package.

**Comment by arne48** [comment]
The behavior of the xmlrpc client slightly changed so in addition to your PR I rearranged the error handling.
With these small changes a disappearing rosmaster will be warned of gracefully both under melodic and noetic.
